x-postgres-common: &postgres-common
  image: postgres:15
  command:
    - "postgres"
    - "-c"
    - "config_file=/etc/postgresql/postgresql.conf"
    - "-c"
    - "hba_file=/etc/postgresql/pg_hba.conf"
  restart: unless-stopped
  ports:
    - "5432:5432"
  shm_size: 1gb
  networks:
    - postgres

services:
  postgres-master:
    <<: *postgres-common
    container_name: "highload-postgres-master"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    build: ./docker/postgres/master
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
      - ./docker/postgres/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/master/pg_hba.conf:/etc/postgresql/pg_hba.conf

  postgres-slave-1:
    <<: *postgres-common
    container_name: "highload-postgres-slave-1"
    ports:
      - "5433:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - postgres-slave-1-data:/var/lib/postgresql/data
      - ./docker/postgres/slave-1/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/slave-1/pg_hba.conf:/etc/postgresql/pg_hba.conf
    depends_on:
      - postgres-master

  postgres-slave-2:
    <<: *postgres-common
    container_name: "highload-postgres-slave-2"
    ports:
      - "5434:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - postgres-slave-2-data:/var/lib/postgresql/data
      - ./docker/postgres/slave-2/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/slave-2/pg_hba.conf:/etc/postgresql/pg_hba.conf
    depends_on:
      - postgres-master

  postgres-slave-3:
    <<: *postgres-common
    container_name: "highload-postgres-slave-3"
    ports:
      - "5435:5432"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - postgres-slave-3-data:/var/lib/postgresql/data
      - ./docker/postgres/slave-3/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/slave-3/pg_hba.conf:/etc/postgresql/pg_hba.conf
    depends_on:
      - postgres-master

  redis:
    image: redis:7.2-alpine
    container_name: "highload-redis"
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: "highload-rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  haproxy:
    image: haproxy:3.0
    container_name: "highload-haproxy"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5488:5488"
    depends_on:
        - postgres-slave-1
        - postgres-slave-2
    networks:
      - postgres

volumes:
  postgres-master-data:
  postgres-slave-1-data:
  postgres-slave-2-data:
  postgres-slave-3-data:
  rabbitmq-data:

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1