port: '8000'

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"

db-slave:
  host: "localhost"
  port: "5433"
  username: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"